com.turankanbur.calculator.IngredientManagement Class Reference
Public Member Functions
IngredientManagement (String name, int price)
void addIngredient (Ingredient ingredient, String file)
List< Ingredient > getIngredients ()
void setIngredient (List< Ingredient > ingredients)
void saveToFile (String fileName)
void loadFromFile (String fileName)
void listIngredients ()
void editIngredientPrice (String ingredientName, int newPrice)
Ingredient findIngredientByName (String name)
Public Member Functions inherited from com.turankanbur.calculator.Ingredient
Ingredient (String name, int price)
String getName ()
int getPrice ()
void setPrice (int price)
Public Attributes
List< Ingredient > ingredients
Detailed Description
Provides functionality for handling end-of-file (EOF) conditions. Provides functionality for reading bytes from a file input stream. Provides functionality for writing bytes to a file output stream. Provides functionality for handling input/output (I/O) operations. Provides functionality for reading objects from an input stream. Provides functionality for writing objects to an output stream. Allows classes to implement serialization, allowing their objects to be converted into byte streams. Provides an implementation of the List interface backed by an array. Provides functionality for storing and manipulating collections of objects. Manages the ingredients used in recipes. This class provides methods for adding, listing, editing, and loading/saving ingredients to/from a file.
Definition at line 58 of file IngredientManagement.java.
Constructor & Destructor Documentation
IngredientManagement()
com.turankanbur.calculator.IngredientManagement.IngredientManagement (String name, int price)
Constructs an IngredientManagement object with the specified name and price for the base ingredient. Initializes the list of ingredients.
Parameters
name the name of the base ingredient
price the price of the base ingredient
Definition at line 80 of file IngredientManagement.java.
                                                        {
        super(name, price);
        this.ingredients = new ArrayList<>();
    }
Referenced by com.turankanbur.calculator.Menu.removeIngredient().
Member Function Documentation
addIngredient()
void com.turankanbur.calculator.IngredientManagement.addIngredient (Ingredient ingredient, String file)
Adds an ingredient to the list of managed ingredients.
Parameters
ingredient the ingredient to add
file the name of the file to save the ingredients to
Definition at line 92 of file IngredientManagement.java.
                                                                  {
        ingredients.add(ingredient);
    }
References com.turankanbur.calculator.IngredientManagement.ingredients.
Referenced by com.turankanbur.calculator.Menu.addIngredient().
editIngredientPrice()
void com.turankanbur.calculator.IngredientManagement.editIngredientPrice (String ingredientName, int newPrice)
Edits the price of a specified ingredient.
Parameters
ingredientName the name of the ingredient to edit
newPrice the new price of the ingredient
Definition at line 190 of file IngredientManagement.java.
                                                                         {
        for (Ingredient ingredient : ingredients) {
            if (ingredient.getName().equals(ingredientName)) {
                ingredient.setPrice(newPrice);
                System.out.println("The price of" + ingredientName + " ingredient has been succesfully updated.");
                // saveToFile("example.bin");
                return;
            }
        }
        System.out.println("The price of specified ingredient could not found.");
    }
References com.turankanbur.calculator.IngredientManagement.ingredients.
findIngredientByName()
Ingredient com.turankanbur.calculator.IngredientManagement.findIngredientByName (String name)
Finds an ingredient by its name.
Parameters
name the name of the ingredient to find
Returns
the ingredient if found, or null if not found
Definition at line 209 of file IngredientManagement.java.
                                                        {
        for (Ingredient ingredient : ingredients) {
            if (ingredient.getName().equalsIgnoreCase(name)) {
                return ingredient;
            }
        }
        return null;
    }
References com.turankanbur.calculator.IngredientManagement.ingredients.
Referenced by com.turankanbur.calculator.Menu.editIngredient(), and com.turankanbur.calculator.Menu.removeIngredient().
getIngredients()
List< Ingredient > com.turankanbur.calculator.IngredientManagement.getIngredients ()
Retrieves the list of managed ingredients.
Returns
the list of managed ingredients
Definition at line 103 of file IngredientManagement.java.
                                             {
        return ingredients;
    }
References com.turankanbur.calculator.IngredientManagement.ingredients.
Referenced by com.turankanbur.calculator.Menu.CreateRecipe(), and com.turankanbur.calculator.Menu.removeIngredient().
listIngredients()
void com.turankanbur.calculator.IngredientManagement.listIngredients ()
Lists all managed ingredients along with their names and prices.
Definition at line 168 of file IngredientManagement.java.
                                  {
        if (ingredients.isEmpty()) {
            System.out.println("No ingredients found to list.");
            return;
        }
        for (int i = 0; i < ingredients.size(); i++) {
            Ingredient ingredient = ingredients.get(i);
            System.out.println("\n" + "Ingredient " + (i + 1) + ":");
            System.out.println(" Name: " + ingredient.getName());
            System.out.println(" Price: " + ingredient.getPrice()+ "$");
            System.out.println("-------------------------\n");
        }
    }
References com.turankanbur.calculator.Ingredient.getName(), com.turankanbur.calculator.Ingredient.getPrice(), and com.turankanbur.calculator.IngredientManagement.ingredients.
Referenced by com.turankanbur.calculator.Menu.editIngredient(), com.turankanbur.calculator.Menu.removeIngredient(), com.turankanbur.calculator.Menu.viewIngredient(), and com.turankanbur.calculator.Menu.viewIngredientForGuest().
loadFromFile()
void com.turankanbur.calculator.IngredientManagement.loadFromFile (String fileName)
Loads ingredients from a file and populates the managed ingredients list.
Parameters
fileName the name of the file to load from
Definition at line 144 of file IngredientManagement.java.
                                              {
        try (FileInputStream fis = new FileInputStream(fileName); ObjectInputStream ois = new ObjectInputStream(fis)) {
            while (true) {
                try {
                    Ingredient loadedIngredient = (Ingredient) ois.readObject();
                    ingredients.add(loadedIngredient);
                    // Read and discard the marker
                    ois.readUTF();
                } catch (EOFException e) {
                    break; // Reached end of file
                }
            }
        } catch (IOException | ClassNotFoundException e) {
            System.err.println("Error loading from file: " + e.getMessage());
        }
    }
References com.turankanbur.calculator.IngredientManagement.ingredients.
Referenced by com.turankanbur.calculator.Menu.addIngredient(), com.turankanbur.calculator.Menu.CreateRecipe(), com.turankanbur.calculator.Menu.editIngredient(), com.turankanbur.calculator.Menu.removeIngredient(), com.turankanbur.calculator.Menu.viewIngredient(), and com.turankanbur.calculator.Menu.viewIngredientForGuest().
saveToFile()
void com.turankanbur.calculator.IngredientManagement.saveToFile (String fileName)
Saves the managed ingredients to a file.
Parameters
fileName the name of the file to save to
Definition at line 122 of file IngredientManagement.java.
                                            {
        try (FileOutputStream fos = new FileOutputStream(fileName);
                ObjectOutputStream oos = new ObjectOutputStream(fos)) {
            for (Ingredient ingredient : ingredients) {
                oos.writeObject(ingredient);
                oos.writeUTF("#END_INGREDIENT#"); // Add a marker between ingredients
            }
            System.err.println("Ingredient has been succesfully saved to file");
        } catch (IOException e) {
            System.err.println("Error saving to file: " + e.getMessage());
        }
    }
References com.turankanbur.calculator.IngredientManagement.ingredients.
Referenced by com.turankanbur.calculator.Menu.addIngredient(), com.turankanbur.calculator.Menu.editIngredient(), and com.turankanbur.calculator.Menu.removeIngredient().
setIngredient()
void com.turankanbur.calculator.IngredientManagement.setIngredient (List< Ingredient > ingredients)
Sets the list of managed ingredients.
Parameters
ingredients the list of ingredients to set
Definition at line 112 of file IngredientManagement.java.
                                                            {
        this.ingredients = ingredients;
    }
References com.turankanbur.calculator.IngredientManagement.ingredients.
Member Data Documentation
ingredients
List<Ingredient> com.turankanbur.calculator.IngredientManagement.ingredients
Manages the ingredients used in recipes. This class provides methods for adding, listing, editing, and loading/saving ingredients to/from a file.
Definition at line 69 of file IngredientManagement.java.
Referenced by com.turankanbur.calculator.IngredientManagement.addIngredient(), com.turankanbur.calculator.IngredientManagement.editIngredientPrice(), com.turankanbur.calculator.IngredientManagement.findIngredientByName(), com.turankanbur.calculator.IngredientManagement.getIngredients(), com.turankanbur.calculator.IngredientManagement.listIngredients(), com.turankanbur.calculator.IngredientManagement.loadFromFile(), com.turankanbur.calculator.IngredientManagement.saveToFile(), and com.turankanbur.calculator.IngredientManagement.setIngredient().
The documentation for this class was generated from the following file:
recipe-cost-calculator-app/src/main/java/com/turankanbur/calculator/IngredientManagement.java