com.turankanbur.calculator.Meal Class Reference
Public Member Functions
Meal (String name, List< Recipe > recipes)
String getName ()
List< Recipe > getRecipes ()
double getTotalCost ()
Detailed Description
Represents a meal consisting of one or more recipes. Provides functionality to calculate the total cost of the meal.
Definition at line 78 of file Meal.java.
Constructor & Destructor Documentation
Meal()
com.turankanbur.calculator.Meal.Meal (String name, List< Recipe > recipes)
Constructs a Meal object with the specified name and list of recipes. Calculates the total cost of the meal.
Parameters
name the name of the meal
recipes the list of recipes included in the meal
Definition at line 107 of file Meal.java.
                                                   {
        this.name = name;
        this.recipes = recipes;
        calculateTotalCost();
    }
Member Function Documentation
getName()
String com.turankanbur.calculator.Meal.getName ()
Retrieves the name of the meal.
Returns
the name of the meal
Definition at line 118 of file Meal.java.
                            {
        return name;
    }
Referenced by com.turankanbur.calculator.MealManagement.listMeals().
getRecipes()
List< Recipe > com.turankanbur.calculator.Meal.getRecipes ()
Retrieves the list of recipes included in the meal.
Returns
the list of recipes
Definition at line 127 of file Meal.java.
                                     {
        return recipes;
    }
getTotalCost()
double com.turankanbur.calculator.Meal.getTotalCost ()
Retrieves the total cost of the meal.
Returns
the total cost of the meal
Definition at line 136 of file Meal.java.
                                 {
        return totalCost;
    }
Referenced by com.turankanbur.calculator.MealManagement.createMealFromUserInput(), and com.turankanbur.calculator.MealManagement.listMeals().
The documentation for this class was generated from the following file:
recipe-cost-calculator-app/src/main/java/com/turankanbur/calculator/Meal.java