com.turankanbur.calculator.MealManagement Class Reference
Public Member Functions
MealManagement ()
void addMeal (Meal meal, String fileName)
List< Meal > getMeals ()
void saveMealsToFile (List< Meal > meals, String fileName)
List< Meal > loadMealsFromFile (String fileName)
void createMealFromUserInput (String mealName, List< Recipe > selectedRecipes, RecipeManagement recipeManager)
void listMeals (String filename)
Public Attributes
List< Meal > meals
Detailed Description
Provides functionality for handling input/output (I/O) operations. Provides the framework for writing programs that manipulate collections of objects. Manages meals, including adding, saving, loading, and listing meals. This class provides functionality to create meals from user input and interact with meal data stored in files.
Definition at line 21 of file MealManagement.java.
Constructor & Destructor Documentation
MealManagement()
com.turankanbur.calculator.MealManagement.MealManagement ()
Constructs a MealManagement object with an empty list of meals.
Definition at line 32 of file MealManagement.java.
                            {
        this.meals = new ArrayList<>();
    }
Member Function Documentation
addMeal()
void com.turankanbur.calculator.MealManagement.addMeal (Meal meal, String fileName)
Adds a meal to the list of managed meals and saves it to a file.
Parameters
meal the meal to add
fileName the name of the file to save the meals to
Definition at line 43 of file MealManagement.java.
                                                    {
        // Load existing meals from file
        List<Meal> existingMeals = loadMealsFromFile(fileName);
        // Add the new meal to the existing list
        existingMeals.add(meal);
        // Save all meals to file
        saveMealsToFile(existingMeals, fileName);
    }
References com.turankanbur.calculator.MealManagement.loadMealsFromFile(), and com.turankanbur.calculator.MealManagement.saveMealsToFile().
Referenced by com.turankanbur.calculator.MealManagement.createMealFromUserInput().
createMealFromUserInput()
void com.turankanbur.calculator.MealManagement.createMealFromUserInput (String mealName, List< Recipe > selectedRecipes, RecipeManagement recipeManager)
Creates a meal from user input and adds it to the list of managed meals.
Parameters
mealName the name of the meal
selectedRecipes the list of recipes included in the meal
recipeManager the RecipeManagement object to interact with recipe data
Definition at line 123 of file MealManagement.java.
                                                                                                                       {
        Meal meal = new Meal(mealName, selectedRecipes);
        addMeal(meal, "meals.bin");
        System.out.println("Meal Name: " + mealName);
        System.out.println("Total Cost: " + meal.getTotalCost()+"$");
        System.out.println("Selected Recipes:");
        for (Recipe selectedRecipe : selectedRecipes) {
            System.out.println("- " + selectedRecipe.getName());
        }
    }
References com.turankanbur.calculator.MealManagement.addMeal(), and com.turankanbur.calculator.Meal.getTotalCost().
Referenced by com.turankanbur.calculator.Menu.CreateMeal().
getMeals()
List< Meal > com.turankanbur.calculator.MealManagement.getMeals ()
Retrieves the list of managed meals.
Returns
the list of managed meals
Definition at line 59 of file MealManagement.java.
                                 {
        return this.meals;
    }
References com.turankanbur.calculator.MealManagement.meals.
listMeals()
void com.turankanbur.calculator.MealManagement.listMeals (String filename)
Lists all managed meals along with their names and total costs.
Parameters
filename the name of the file to load meals from
Definition at line 141 of file MealManagement.java.
                                           {
        // Load recipes from file
        meals = loadMealsFromFile(filename);
        if (meals.isEmpty()) {
            System.out.println("No recipes found to list.");
            return;
        }
        for (int i = 0; i < meals.size(); i++) {
            Meal meal = meals.get(i);
            System.out.println("\nMeal " + (i + 1) + ":");
            System.out.println(" Name: " + meal.getName());
            System.out.println(" Total Cost: " + meal.getTotalCost()+ "$");
        }
        System.out.println("-------------------------\n");
    }
References com.turankanbur.calculator.Meal.getName(), com.turankanbur.calculator.Meal.getTotalCost(), com.turankanbur.calculator.MealManagement.loadMealsFromFile(), and com.turankanbur.calculator.MealManagement.meals.
Referenced by com.turankanbur.calculator.Menu.viewMeal(), and com.turankanbur.calculator.Menu.viewMealForGuest().
loadMealsFromFile()
List< Meal > com.turankanbur.calculator.MealManagement.loadMealsFromFile (String fileName)
Loads meals from a file and returns them as a list.
Parameters
fileName the name of the file to load from
Returns
the list of loaded meals
Definition at line 91 of file MealManagement.java.
                                                         {
        List<Meal> loadedMeals = new ArrayList<>();
        try (FileInputStream fis = new FileInputStream(fileName); ObjectInputStream ois = new ObjectInputStream(fis)) {
            while (true) {
                try {
                    Meal loadedMeal = (Meal) ois.readObject();
                    loadedMeals.add(loadedMeal);
                    ois.readUTF();
                } catch (EOFException e) {
                    break; // Reached end of file
                }
            }
        } catch (IOException | ClassNotFoundException e) {
        }
        return loadedMeals;
    }
Referenced by com.turankanbur.calculator.MealManagement.addMeal(), and com.turankanbur.calculator.MealManagement.listMeals().
saveMealsToFile()
void com.turankanbur.calculator.MealManagement.saveMealsToFile (List< Meal > meals, String fileName)
Saves a list of meals to a file.
Parameters
meals the list of meals to save
fileName the name of the file to save to
Definition at line 70 of file MealManagement.java.
                                                                   {
        try (FileOutputStream fos = new FileOutputStream(fileName);
                ObjectOutputStream oos = new ObjectOutputStream(fos)) {
            for (Meal meal : meals) {
                oos.writeObject(meal);
                oos.writeUTF("#END_MEAL#");
            }
        } catch (IOException e) {
            System.err.println("Error saving meals to file: " + e.getMessage());
        }
    }
References com.turankanbur.calculator.MealManagement.meals.
Referenced by com.turankanbur.calculator.MealManagement.addMeal().
Member Data Documentation
meals
List<Meal> com.turankanbur.calculator.MealManagement.meals
List of meals managed by this MealManagement instance.
Definition at line 29 of file MealManagement.java.
Referenced by com.turankanbur.calculator.MealManagement.getMeals(), com.turankanbur.calculator.MealManagement.listMeals(), and com.turankanbur.calculator.MealManagement.saveMealsToFile().
The documentation for this class was generated from the following file:
recipe-cost-calculator-app/src/main/java/com/turankanbur/calculator/MealManagement.java