com.turankanbur.calculator.Ingredient Class Reference
Public Member Functions
Ingredient (String name, int price)
String getName ()
int getPrice ()
void setPrice (int price)
Detailed Description
Represents an ingredient used in a recipe. This class provides methods to get and set the name and price of the ingredient.
Definition at line 73 of file Ingredient.java.
Constructor & Destructor Documentation
Ingredient()
com.turankanbur.calculator.Ingredient.Ingredient (String name, int price)
Constructs an Ingredient object with the specified name and price.
Parameters
name the name of the ingredient
price the price of the ingredient
Definition at line 97 of file Ingredient.java.
                                              {
        this.name = name;
        this.price = price;
    }
Member Function Documentation
getName()
String com.turankanbur.calculator.Ingredient.getName ()
Retrieves the name of the ingredient.
Returns
the name of the ingredient
Definition at line 107 of file Ingredient.java.
                            {
        return name;
    }
Referenced by com.turankanbur.calculator.Menu.CreateRecipe(), com.turankanbur.calculator.IngredientManagement.listIngredients(), and com.turankanbur.calculator.RecipeManagement.listRecipes().
getPrice()
int com.turankanbur.calculator.Ingredient.getPrice ()
Retrieves the price of the ingredient.
Returns
the price of the ingredient
Definition at line 119 of file Ingredient.java.
                          {
        return price;
    }
Referenced by com.turankanbur.calculator.Menu.CreateRecipe(), com.turankanbur.calculator.IngredientManagement.listIngredients(), and com.turankanbur.calculator.RecipeManagement.listRecipes().
setPrice()
void com.turankanbur.calculator.Ingredient.setPrice (int price)
Sets the price of the ingredient.
Parameters
price the price to be set
Definition at line 128 of file Ingredient.java.
                                    {
        this.price = price;
    }
Referenced by com.turankanbur.calculator.Menu.editIngredient().
The documentation for this class was generated from the following file:
recipe-cost-calculator-app/src/main/java/com/turankanbur/calculator/Ingredient.java