com.turankanbur.calculator.Recipe Class Reference
Public Member Functions
Recipe (String name, List< Ingredient > ingredients, double totalCost)
String getName ()
List< Ingredient > getIngredients ()
double getTotalCost ()
int getQuantity ()
void setQuantity (int quantity)
void setTotalCost (double totalCost)
Detailed Description
Provides functionality for serialization, allowing objects to be converted into byte streams. Provides functionality for storing and manipulating collections of objects. Represents a recipe consisting of a name, ingredients, quantity, and total cost. Provides methods to access and modify recipe information.
Definition at line 22 of file Recipe.java.
Constructor & Destructor Documentation
Recipe()
com.turankanbur.calculator.Recipe.Recipe (String name, List< Ingredient > ingredients, double totalCost)
Constructs a Recipe object with the specified name, ingredients, and total cost.
Parameters
name the name of the recipe
ingredients the list of ingredients required for the recipe
totalCost the total cost of the recipe
Definition at line 49 of file Recipe.java.
                                                                               {
        this.name = name;
        this.ingredients = ingredients;
        this.totalCost = totalCost;
    }
Member Function Documentation
getIngredients()
List< Ingredient > com.turankanbur.calculator.Recipe.getIngredients ()
Retrieves the list of ingredients required for the recipe.
Returns
the list of ingredients
Definition at line 69 of file Recipe.java.
                                             {
        return ingredients;
    }
Referenced by com.turankanbur.calculator.RecipeManagement.listRecipes().
getName()
String com.turankanbur.calculator.Recipe.getName ()
Retrieves the name of the recipe.
Returns
the name of the recipe
Definition at line 60 of file Recipe.java.
                            {
        return name;
    }
Referenced by com.turankanbur.calculator.Menu.CreateMeal(), and com.turankanbur.calculator.RecipeManagement.listRecipes().
getQuantity()
int com.turankanbur.calculator.Recipe.getQuantity ()
Retrieves the quantity of the recipe.
Returns
the quantity of the recipe
Definition at line 87 of file Recipe.java.
                             {
        return quantity;
    }
getTotalCost()
double com.turankanbur.calculator.Recipe.getTotalCost ()
Retrieves the total cost of the recipe.
Returns
the total cost of the recipe
Definition at line 78 of file Recipe.java.
                                 {
        return totalCost;
    }
Referenced by com.turankanbur.calculator.RecipeManagement.listRecipes().
setQuantity()
void com.turankanbur.calculator.Recipe.setQuantity (int quantity)
Sets the quantity of the recipe.
Parameters
quantity the quantity of the recipe to set
Definition at line 96 of file Recipe.java.
                                          {
        this.quantity = quantity;
    }
setTotalCost()
void com.turankanbur.calculator.Recipe.setTotalCost (double totalCost)
Sets the total cost of the recipe.
Parameters
totalCost the total cost of the recipe to set
Definition at line 105 of file Recipe.java.
                                               {
        this.totalCost = totalCost;
    }
The documentation for this class was generated from the following file:
recipe-cost-calculator-app/src/main/java/com/turankanbur/calculator/Recipe.java