com.turankanbur.calculator.RecipeManagement Class Reference
Public Member Functions
RecipeManagement ()
void addRecipe (Recipe recipe, String fileName)
List< Recipe > getRecipes ()
void listRecipes (String filename)
void setRecipes (List< Recipe > recipes2)
Static Public Member Functions
static void saveToFile (List< Recipe > recipes, String fileName)
static List< Recipe > loadFromFile (String fileName)
static void createRecipeFromUserInput (List< Ingredient > availableIngredients, RecipeManagement recipeManager, String recipeName, double totalCost, List< Ingredient > selectedIngredients)
Detailed Description
Provides functionality for handling end-of-file (EOF) conditions. Provides functionality for reading bytes from a file input stream. Provides functionality for writing bytes to a file output stream. Provides functionality for handling input/output (I/O) operations. Provides functionality for reading objects from an input stream. Provides functionality for writing objects to an output stream. Allows classes to implement serialization, allowing their objects to be converted into byte streams. Provides an implementation of the List interface backed by an array. Provides functionality for storing and manipulating collections of objects. Manages recipes, including adding, saving, loading, and listing recipes. This class provides functionality to create recipes from user input and interact with recipe data stored in files.
Definition at line 56 of file RecipeManagement.java.
Constructor & Destructor Documentation
RecipeManagement()
com.turankanbur.calculator.RecipeManagement.RecipeManagement ()
Constructs a RecipeManagement object with an empty list of recipes.
Definition at line 67 of file RecipeManagement.java.
                              {
        
        this.recipes = new ArrayList<>();
    }
Member Function Documentation
addRecipe()
void com.turankanbur.calculator.RecipeManagement.addRecipe (Recipe recipe, String fileName)
Adds a recipe to the list of managed recipes and saves it to a file.
Parameters
recipe the recipe to add
fileName the name of the file to save the recipes to
Definition at line 80 of file RecipeManagement.java.
                                                          {
        // Load existing recipes from file
        List<Recipe> existingRecipes = loadFromFile(fileName);
        // Add the new recipe to the existing list
        existingRecipes.add(recipe);
        // Save all recipes to file
        saveToFile(existingRecipes, fileName);
    }
References com.turankanbur.calculator.RecipeManagement.loadFromFile(), and com.turankanbur.calculator.RecipeManagement.saveToFile().
Referenced by com.turankanbur.calculator.RecipeManagement.createRecipeFromUserInput().
createRecipeFromUserInput()
static void com.turankanbur.calculator.RecipeManagement.createRecipeFromUserInput (List< Ingredient > availableIngredients, RecipeManagement recipeManager, String recipeName, double totalCost, List< Ingredient > selectedIngredients) [static]
Creates a recipe from user input and adds it to the list of managed recipes.
Parameters
availableIngredients the list of available ingredients
recipeManager the RecipeManagement object to interact with recipe data
recipeName the name of the recipe
totalCost the total cost of the recipe
selectedIngredients the list of selected ingredients for the recipe
Definition at line 159 of file RecipeManagement.java.
                                                                                       {
        // Print recipe details
        System.out.println("\nRecipe Name: " + recipeName);
        System.out.println("Total Cost: " + totalCost + "$");
        System.out.println("Ingredients:");
        for (Ingredient ingredient : selectedIngredients) {
            System.out.println("- " + ingredient.getName() + ": " + ingredient.getPrice() + "$" + " per unit");
        }
        // Create the recipe
        Recipe recipe = new Recipe(recipeName, selectedIngredients, totalCost);
        // Add the recipe to the existing recipe manager and save to file
        recipeManager.addRecipe(recipe, "recipes.bin");
    }
References com.turankanbur.calculator.RecipeManagement.addRecipe().
Referenced by com.turankanbur.calculator.Menu.CreateRecipe().
getRecipes()
List< Recipe > com.turankanbur.calculator.RecipeManagement.getRecipes ()
Retrieves the list of managed recipes.
Returns
the list of managed recipes
Definition at line 96 of file RecipeManagement.java.
                                     {
        return this.recipes;
    }
Referenced by com.turankanbur.calculator.Menu.CreateMeal().
listRecipes()
void com.turankanbur.calculator.RecipeManagement.listRecipes (String filename)
Lists all managed recipes along with their names, total costs, and ingredients.
Parameters
filename the name of the file to load recipes from
Definition at line 185 of file RecipeManagement.java.
                                             {
        // Load recipes from file
        recipes = loadFromFile(filename);
        if (recipes.isEmpty()) {
            System.out.println("No recipes found to list.");
            return;
        }
        for (int i = 0; i < recipes.size(); i++) {
            Recipe recipe = recipes.get(i);
            System.out.println("\nRecipe " + (i + 1) + ":");
            System.out.println(" Name: " + recipe.getName());
            System.out.println(" Total Cost: " + recipe.getTotalCost()+ "$");
            System.out.println(" Ingredients:");
            List<Ingredient> ingredients = recipe.getIngredients();
            for (int j = 0; j < ingredients.size(); j++) {
                Ingredient ingredient = ingredients.get(j);
                System.out.println(" - " + ingredient.getName() + ": " + ingredient.getPrice ()+ "$" + " per unit");
            }
        }
        System.out.println("-------------------------\n");
    }
References com.turankanbur.calculator.Recipe.getIngredients(), com.turankanbur.calculator.Ingredient.getName(), com.turankanbur.calculator.Recipe.getName(), com.turankanbur.calculator.Ingredient.getPrice(), com.turankanbur.calculator.Recipe.getTotalCost(), and com.turankanbur.calculator.RecipeManagement.loadFromFile().
Referenced by com.turankanbur.calculator.Menu.CreateMeal(), com.turankanbur.calculator.Menu.viewRecipe(), and com.turankanbur.calculator.Menu.viewRecipeForGuest().
loadFromFile()
static List< Recipe > com.turankanbur.calculator.RecipeManagement.loadFromFile (String fileName) [static]
Loads recipes from a file and returns them as a list.
Parameters
fileName the name of the file to load from
Returns
the list of loaded recipes
Definition at line 126 of file RecipeManagement.java.
                                                             {
        List<Recipe> loadedRecipes = new ArrayList<>();
        try (FileInputStream fis = new FileInputStream(fileName); ObjectInputStream ois = new ObjectInputStream(fis)) {
            while (true) {
                try {
                    Recipe loadedRecipe = (Recipe) ois.readObject();
                    loadedRecipes.add(loadedRecipe);
                    ois.readUTF();
                } catch (EOFException e) {
                    break; // Reached end of file
                }
            }
        } catch (IOException | ClassNotFoundException e) {
            System.err.println("Error loading from file: " + e.getMessage());
        }
        return loadedRecipes;
    }
Referenced by com.turankanbur.calculator.RecipeManagement.addRecipe(), com.turankanbur.calculator.Menu.CreateMeal(), com.turankanbur.calculator.RecipeManagement.listRecipes(), and com.turankanbur.calculator.Menu.RecipeCosting().
saveToFile()
static void com.turankanbur.calculator.RecipeManagement.saveToFile (List< Recipe > recipes, String fileName) [static]
Saves a list of recipes to a file.
Parameters
recipes the list of recipes to save
fileName the name of the file to save to
Definition at line 106 of file RecipeManagement.java.
                                                                         {
        try (FileOutputStream fos = new FileOutputStream(fileName);
                ObjectOutputStream oos = new ObjectOutputStream(fos)) {
            for (Recipe r : recipes) {
                oos.writeObject(r);
                oos.writeUTF("#END_RECIPE#");
            }
        } catch (IOException e) {
            System.err.println("Error saving to file: " + e.getMessage());
        }
    }
Referenced by com.turankanbur.calculator.RecipeManagement.addRecipe().
setRecipes()
void com.turankanbur.calculator.RecipeManagement.setRecipes (List< Recipe > recipes2)
Sets the list of recipes managed by this RecipeManagement instance.
Parameters
recipes2 the list of recipes to set
Definition at line 215 of file RecipeManagement.java.
                                                  {
        this.recipes = recipes2;
    }
The documentation for this class was generated from the following file:
recipe-cost-calculator-app/src/main/java/com/turankanbur/calculator/RecipeManagement.java